services:
  react-weather-app:
    container_name: react-weather-app
    build:
      context: .
      dockerfile: docker-prod.Dockerfile
      args:
        NEXT_PUBLIC_OPEN_WEATHER_API_KEY: ${NEXT_PUBLIC_OPEN_WEATHER_API_KEY}
    restart: always
    ports:
      - "3000:3000"
    networks:
      - react-weather-app-network

networks:
  react-weather-app-network:
    external: true