services:
  react-weather-app:
    container_name: react-weather-app
    build:
      context: .
      dockerfile: docker-dev.Dockerfile
    environment:
      NEXT_PUBLIC_OPEN_WEATHER_API_KEY: ${NEXT_PUBLIC_OPEN_WEATHER_API_KEY}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - react-weather-app-network

networks:
  react-weather-app-network:
    external: true